name: nattygaslab
description: "Natty Gas Lab LIMS prototype"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # UI
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # Firebase Core & Services
  firebase_core: ^3.3.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.4.0

  # State Management (simple)
  provider: ^6.1.2

  
  # Cloud Storage
  cloudinary: ^1.1.0

  # Image handling
  image_picker: ^1.0.4
  http: ^1.1.0

  dotted_border: ^2.1.0
  
  # Additional dependencies for new features
  shared_preferences: ^2.2.2
  path_provider: ^2.1.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
