// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6Vz3BJiZ-UDviXT9mX5euqdT9gnCO_4M',
    appId: '1:538315850223:web:3b4c6211e981c4052a761a',
    messagingSenderId: '538315850223',
    projectId: 'nattygaslab',
    authDomain: 'nattygaslab.firebaseapp.com',
    storageBucket: 'nattygaslab.appspot.com', // ✅ fixed
    measurementId: 'G-X901SSQ7H2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzrOCqF_WaK2bE-DrcMYVEKwP4EnIfvqc',
    appId: '1:538315850223:android:5488e118bffada3f2a761a',
    messagingSenderId: '538315850223',
    projectId: 'nattygaslab',
    storageBucket: 'nattygaslab.appspot.com', // ✅ fixed
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhgcvClWF84gKJUkeq81lNhU54dAoMIdQ',
    appId: '1:538315850223:ios:03f17c90de5832292a761a',
    messagingSenderId: '538315850223',
    projectId: 'nattygaslab',
    storageBucket: 'nattygaslab.appspot.com', // ✅ fixed
    iosBundleId: 'com.example.nattygaslab',
  );
}
